server:
  port: 8083
spring:
  application:
    name: Dealer-App
  data:
    mongodb:
      uri: mongodb+srv://AshwinDavid:xxxxxxx@cluster0-training.1p0c1.mongodb.net/DealerDB?retryWrites=true&w=majority
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
