server:
  port: 8088
spring:
  application:
    name: UserMicroservice
  data:
    mongodb:
      uri: mongodb+srv://AshwinDavid:19_valsalakumari_62@cluster0-training.1p0c1.mongodb.net/FarmerDB?retryWrites=true&w=majority
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
