server:
   port: 8100
      
spring:
  application:
    name: ZuulGateway
    
zuul:
   routes:
      DEALER-APP:
         serviceId: DEALER-APP
      FARMER-APP:
         serviceId: FARMER-APP
      ADMINMICROSERVICE:
         serviceId: ADMINMICROSERVICE
      CROPMICROSERVICE:
         serviceId: CROPMICROSERVICE
      ORDERMICROSERVICE:
         serviceId: ORDERMICROSERVICE
      PAYMENTMICROSERVICE:
         serviceId: PAYMENTMICROSERVICE
      USERMICROSERVICE:
         serviceId: USERMICROSERVICE